version: '3'

services:
  db-sql:
    container_name: postgres-dev-db
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

  db-mongo:
    container_name: mongo-dev-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
